# Generated by Django 5.0.6 on 2024-06-26 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vechile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gps_tracking_no', models.CharField(max_length=200)),
                ('sim_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GPSDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('joined_date', models.CharField(max_length=200)),
                ('using_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vechile_driver', to='homepage.vechile')),
            ],
        ),
        migrations.CreateModel(
            name='VechileMaitenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('vechile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vechile_maitanance', to='homepage.vechile')),
            ],
        ),
    ]
