# Generated by Django 5.0.6 on 2024-07-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_vechile_number_plate_vechiledriver_delete_gpsdriver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vechile',
            name='sim_number',
        ),
    ]
